export const blogs = [
  {
    id: "1",
    title: "How to Start Earning Online",
    shortDescription: "Learn the exact steps to launch your online journey from scratch and start earning...",
    image: "https://source.unsplash.com/random/400x200?growth",
    category: "Tips Marketing",
    filename: "blog-how-to-start-earning-online.html",
    fullContent: "<p>This is the full content for 'How to Start Earning Online'. You can replace this placeholder with your detailed blog post.</p><p>It includes steps, tips, and insights to guide users.</p>",
  },
  {
    id: "2",
    title: "The Power of Positive Mindset for Success",
    shortDescription: "Cultivate optimism, resilience, and a growth mindset to achieve your goals.",
    image: "Images/blog-the-power-of-positive-mindset/1.jpg",
    category: "Mindset Tips",
    filename: "blog-the-power-of-positive-mindset.html",
    fullContent: "<p>This is the full content for 'The Power of Positive Mindset for Success'. Develop an optimistic outlook, build resilience, and foster a growth mindset to achieve your professional and personal goals.</p>",
  },
  {
    id: "3",
    title: "Mastering Time Management for Increased Productivity",
    shortDescription: "Take control of your schedule, reduce procrastination, and boost daily productivity.",
    image: "https://source.unsplash.com/random/400x200?time-management",
    category: "Productivity Tips",
    filename: "blog-mastering-time-management.html",
    fullContent: "<p>This is the full content for 'Mastering Time Management for Increased Productivity'. Learn effective strategies to manage your time, overcome procrastination, and significantly boost your daily productivity. This post covers techniques like the Pomodoro method, Eisenhower Matrix, and time blocking.</p>",
  },
  {
    id: "4",
    title: "Effective Digital Marketing Strategies for Beginners",
    shortDescription: "Learn fundamental strategies to reach a wider audience and grow your online presence.",
    image: "https://source.unsplash.com/random/400x200?digital-marketing",
    category: "Marketing Tips",
    filename: "blog-effective-digital-marketing.html",
    fullContent: "<p>This is the full content for 'Effective Digital Marketing Strategies for Beginners'. Discover fundamental strategies to reach a wider audience and grow your online presence. Topics include SEO basics, social media marketing, content creation, and email campaigns.</p>",
  },
  {
    id: "5",
    title: "Building a Strong Personal Brand Online",
    shortDescription: "Define your unique value, create compelling content, and showcase your expertise.",
    image: "https://source.unsplash.com/random/400x200?personal-brand",
    category: "Marketing Tips",
    filename: "blog-building-personal-brand.html",
    fullContent: "<p>This is the full content for 'Building a Strong Personal Brand Online'. Learn how to define your unique value proposition, create compelling content that resonates with your audience, and effectively showcase your expertise to build a powerful personal brand.</p>",
  },
  {
    id: "6",
    title: "The Importance of Networking in Your Career",
    shortDescription: "Build genuine relationships that can significantly impact your career trajectory.",
    image: "https://source.unsplash.com/random/400x200?networking",
    category: "Career Tips",
    filename: "blog-importance-of-networking.html",
    fullContent: "<p>This is the full content for 'The Importance of Networking in Your Career'. Explore how building genuine relationships can significantly impact your career trajectory. This post covers strategies for effective networking, maintaining connections, and leveraging your network for growth.</p>",
  },
  {
    id: "7",
    title: "Unlocking Your Creative Potential",
    shortDescription: "Explore techniques and habits to tap into your innate creative potential.",
    image: "https://source.unsplash.com/random/400x200?creativity",
    category: "Mindset Tips",
    filename: "blog-unlocking-creative-potential.html",
    fullContent: "<p>This is the full content for 'Unlocking Your Creative Potential'. Discover techniques and habits that help you tap into your innate creative potential. This article provides exercises and insights to foster innovation and imaginative thinking.</p>",
  },
  {
    id: "8",
    title: "Financial Freedom: A Step-by-Step Guide",
    shortDescription: "Budgeting, saving, investing, and debt reduction for a secure financial future.",
    image: "https://source.unsplash.com/random/400x200?finance",
    category: "Finance Tips",
    filename: "blog-financial-freedom.html",
    fullContent: "<p>This is the full content for 'Financial Freedom: A Step-by-Step Guide'. Learn how to achieve a secure financial future through effective budgeting, smart saving strategies, wise investing, and systematic debt reduction.</p>",
  },
  {
    id: "9",
    title: "Healthy Habits for a Productive Day",
    shortDescription: "Incorporate routines to boost energy, focus, and overall well-being.",
    image: "https://source.unsplash.com/random/400x200?healthy-habits",
    category: "Health Tips",
    filename: "blog-healthy-habits.html",
    fullContent: "<p>This is the full content for 'Healthy Habits for a Productive Day'. Discover essential routines and practices that can boost your energy, improve focus, and enhance your overall well-being, leading to a more productive day.</p>",
  },
  {
    id: "10",
    title: "Overcoming Procrastination and Achieving Goals",
    shortDescription: "Conquer procrastination, stay motivated, and consistently move towards your objectives.",
    image: "https://source.unsplash.com/random/400x200?procrastination",
    category: "Productivity Mindset Tips",
    filename: "blog-overcoming-procrastination.html",
    fullContent: "<p>This is the full content for 'Overcoming Procrastination and Achieving Goals'. Learn practical strategies to conquer procrastination, maintain motivation, and consistently work towards achieving your objectives. This post offers actionable advice and psychological insights.</p>",
  },
  {
    id: "11",
    title: "The Art of Effective Communication",
    shortDescription: "Convey messages clearly, listen actively, and build rapport for better outcomes.",
    image: "https://source.unsplash.com/random/400x200?communication",
    category: "Communication Tips",
    filename: "blog-effective-communication.html",
    fullContent: "<p>This is the full content for 'The Art of Effective Communication'. Master the essential skills to convey messages clearly, listen actively, and build strong rapport. This post provides techniques for improving both verbal and non-verbal communication for better personal and professional outcomes.</p>",
  },
];
